#DUMMY COMPOSE - WE ARE FOCUSED ON THE DEV ONE FOR NOW
version: "3.9"

networks:
  distichain:
    external:
      name: distichain.localhost

services:
  mp-frontend:
    build:
      context: .
      dockerfile: Dockerfile-alberto
    networks:
      - distichain
    ports:

    - 8080:80

volumes:
  db-data:
