export const TfaTypeEnum = Object.freeze({
  DISABLED: "TWOFA_DISABLED",
  PER_30_DAYS: "PER_30_DAYS",
  EVERY_LOGIN: "EVERY_LOGIN",
  WHATSAPP_PER_30_DAYS: "TWOFA_WHATSAPP_EVERY_30_DAYS",
  WHATSAPP_EVERY_LOGIN: "TWOFA_WHATSAPP_EVERY_LOGIN",
  EMAIL_PER_30_DAYS: "TWOFA_EMAIL_EVERY_30_DAYS",
  EMAIL_EVERY_LOGIN: "TWOFA_EMAIL_EVERY_LOGIN",
  SMS_PER_30_DAYS: "TWOFA_SMS_EVERY_30_DAYS",
  SMS_EVERY_LOGIN: "TWOFA_SMS_EVERY_LOGIN",
  GA_PER_30_DAYS: "TWOFA_GA_EVERY_30_DAYS",
  GA_EVERY_LOGIN: "TWOFA_GA_EVERY_LOGIN"
});
export const FrequencyTypesEnum = {
  PER_30_DAYS: "PER_30_DAYS",
  EVERY_LOGIN: "EVERY_LOGIN"
};
export const MethodEnum = {
  EMAIL: "EMAIL",
  SMS: "SMS",
  GA: "GA"
};
export const MethodLabelEnum = {
  SMS: "SMS",
  GA: "Google Authentication",
  EMAIL: "Email"
};
