import range from "lodash/range";

export const USER_TABS_NAME = Object.freeze({
  profileInfo: "profile-info",
  companyInfo: "company-info",
  ownerInfo: "owner-info",
  bankDetails: "bank-details",
  documents: "uploaded-documents",
  security: "add-credit-security",
  settings: "settings"
});

export const NOTIFICATION_CHANNELS = Object.freeze({
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
  WEB: "WEB"
});

export const USER_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED"
});

export const COMPANY_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  IN_PROGRESS: "IN_PROGRESS",
  INACTIVE: "INACTIVE"
});

export const DOCUMENT_TYPES = Object.freeze({
  TRADE_LICENSE: "Trade License",
  GOOD_CREDIT_CERTIFICATE: "Good Credit Certificate"
});

export const DOCUMENT_DETAILS_TYPES = Object.freeze({
  TRADE_LICENSE_FRONT: "Trade License front image",
  TRADE_LICENSE_BACK: "Trade License back image",
  TRADE_LICENSE_LIVE: "Trade License live image",
  GOOD_CREDIT_CERTIFICATE_FRONT: "Good Credit Certificate front image",
  GOOD_CREDIT_CERTIFICATE_BACK: "Good Credit Certificate back image",
  GOOD_CREDIT_CERTIFICATE_LIVE: "Good Credit Certificate live image"
});

export const DATE_FORMAT = "YYYY-MM-DD";
export const DATETIME_FORMAT = "YYYY-MM-DD HH:mm A";
export const HH_MM_FORMAT = "HH:mm";

export const PRODUCT_WARRANTY_TYPES = Object.freeze({
  WARRANTY: "Warranty",
  NO_WARRANTY: "No Warranty"
});

export const PHONE_OPERATOR_LIMIT_TYPES = Object.freeze({
  NEVER_LOCKED: "Phone Never Locked",
  LOCKED_BY_OPERATOR: "Phone Locked by Operator",
  OPERATOR_UNLOCKED: "Operator Phone Unlocked"
});

export const PHONE_CREDIT_TYPES = Object.freeze({
  SEVEN_DAYS: "7",
  FOURTEEN_DAYS: "14",
  TWENTYONE_DAYS: "21",
  TWENTYEIGHT_DAYS: "28",
  THIRTYFIVE_DAYS: "35"
});

export const FINANCIAL_TURNOVER = [
  {
    name: "",
    text: "10-25 Million $",
    value: ""
  },
  {
    name: "",
    text: "25-50 Million $",
    value: ""
  },
  {
    name: "",
    text: "50-100 Million $",
    value: ""
  },
  {
    name: "",
    text: "more than 100 Million $",
    value: ""
  }
];

export const GENERAL_YEARS = range(1970, 2020);

export const FINANCIAL_YEARS = range(2000, 2020);

export const BID_TYPE = Object.freeze({
  NEW_CREATED: "NEW_CREATED",
  FIRST: "FIRST",
  COUNTER: "COUNTER",
  COUNTER_APPROVING: "COUNTER_APPROVING",
  FINAL: "FINAL"
});

export const BID_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCEL: "CANCELLED",
  EXPIRED: "EXPIRED",
  DELETED: "DELETED",
  APPROVED: "APPROVED",
  INPROGRESS: "IN PROGRESS"
});

export const PAYMENT_METHODS = Object.freeze({
  MY_WALLET: "From my wallet"
});

export const SORT_ORDERS = Object.freeze({
  DESC: "desc",
  ASC: "asc"
});

export const ORDER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ACCEPTED: "ACCEPTED",
  SHIPPING: "SHIPPING",
  INSPECTED: "INSPECTED",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID: "PAID",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  FAILED_INSPECTION: "FAILED_INSPECTION",
  FAILED_PAYMENT: "FAILED_PAYMENT",
  CANCEL: "CANCEL",
  ACTION_REQUIRED: "ACTION_REQUIRED",
  IN_PROGRESS: "IN_PROGRESS"
});

export const ORDER_STATUS_LABEL = Object.freeze({
  [ORDER_STATUS.ACTIVE]: "ACTIVE",
  [ORDER_STATUS.ACCEPTED]: "ACCEPTED",
  [ORDER_STATUS.SHIPPING]: "SHIPPING",
  [ORDER_STATUS.INSPECTED]: "INSPECTED",
  [ORDER_STATUS.PENDING_PAYMENT]: "PENDING PAYMENT",
  [ORDER_STATUS.PAID]: "PAID",
  [ORDER_STATUS.COMPLETED]: "COMPLETED",
  [ORDER_STATUS.REJECTED]: "REJECTED",
  [ORDER_STATUS.FAILED_INSPECTION]: "FAILED INSPECTION",
  [ORDER_STATUS.FAILED_PAYMENT]: "FAILED PAYMENT",
  [ORDER_STATUS.CANCEL]: "CANCEL",
  [ORDER_STATUS.ACTION_REQUIRED]: "ACTION REQUIRED",
  [ORDER_STATUS.IN_PROGRESS]: "IN PROGRESS"
});

export const ORDER_PROCESS = Object.freeze({
  OFFER_APPROVED: "OFFER_APPROVED",
  UPLOAD_SHIPPING_DOCUMENTS: "UPLOAD_SHIPPING_DOCUMENTS",
  INSPECTION: "INSPECTION",
  DONE: "DONE",
  CANCEL: "CANCEL",
  REVIEW: "REVIEW",
  GENERATE_TAX_INVOICE: "GENERATE_TAX_INVOICE",
  CHOOSE_THIRD_PARTY_PROVIDER: "CHOOSE_THIRD_PARTY_PROVIDER",
  CHOOSE_LOGISTICS_PROVIDER: "CHOOSE_LOGISTICS_PROVIDER",
  PROVIDE_SHIPPING_DETAILS: "PROVIDE_SHIPPING_DETAILS",
  CONFIRM_PICKUP_DATE: "CONFIRM_PICKUP_DATE",
  TRACK_SHIPMENT: "TRACK_SHIPMENT",
  SHIPMENT_PICKUP: "SHIPMENT_PICKUP",
  SHIPMENT_REACH_BUYER_WAREHOUSE: "SHIPMENT_REACH_BUYER_WAREHOUSE"
});

export const ORDER_PROCESS_LABEL = Object.freeze({
  [ORDER_PROCESS.OFFER_APPROVED]: "OFFER APPROVED",
  [ORDER_PROCESS.UPLOAD_SHIPPING_DOCUMENTS]: "UPLOAD SHIPPING DOCUMENTS",
  [ORDER_PROCESS.INSPECTION]: "INSPECTION",
  [ORDER_PROCESS.DONE]: "DONE",
  [ORDER_PROCESS.CANCEL]: "CANCEL",
  [ORDER_PROCESS.REVIEW]: "REVIEW",
  [ORDER_PROCESS.GENERATE_TAX_INVOICE]: "GENERATE TAX INVOICE",
  [ORDER_PROCESS.CHOOSE_THIRD_PARTY_PROVIDER]: "CHOOSE THIRD PARTY PROVIDER"
  // [ORDER_PROCESS.FIRST_BID_AS_BUYER]: "First bid as buyer",
  // [ORDER_PROCESS.FINAL_BID_AS_BUYER]: "Final bid as buyer",
  // [ORDER_PROCESS.COUNTER_BID_AS_SELLER]: "Counter bid as seller",
  // [ORDER_PROCESS.REJECTED_BID_AS_SELLER]: "Rejected bid as seller",
  // [ORDER_PROCESS.PRODUCT_DELETED_AS_SELLER]: "product deleted as seller"
});

export const SELLER_ORDER_PROCESS_LABEL = Object.freeze({
  [ORDER_PROCESS.OFFER_APPROVED]: "Offer Approved",
  [ORDER_PROCESS.UPLOAD_SHIPPING_DOCUMENTS]: "Upload Serial Number",
  [ORDER_PROCESS.INSPECTION]: "Buyer Inspection Report",
  [ORDER_PROCESS.DONE]: "Done",
  [ORDER_PROCESS.CANCEL]: "Cancel",
  [ORDER_PROCESS.REVIEW]: "Review",
  [ORDER_PROCESS.GENERATE_TAX_INVOICE]: "Generate Tax Invoice",
  [ORDER_PROCESS.CHOOSE_THIRD_PARTY_PROVIDER]: "Choose Third Party Provider",
  [ORDER_PROCESS.FIRST_BID_AS_BUYER]: "First bid as buyer",
  [ORDER_PROCESS.FINAL_BID_AS_BUYER]: "Final bid as buyer",
  [ORDER_PROCESS.COUNTER_BID_AS_SELLER]: "Counter bid as seller",
  [ORDER_PROCESS.REJECTED_BID_AS_SELLER]: "Rejected bid as seller",
  [ORDER_PROCESS.PRODUCT_DELETED_AS_SELLER]: "product deleted as seller",
  [ORDER_PROCESS.PROVIDE_SHIPPING_DETAILS]: "Provide Shipping Details",
  [ORDER_PROCESS.CHOOSE_LOGISTICS_PROVIDER]: "Buyer to choose logistics provider",
  [ORDER_PROCESS.CONFIRM_PICKUP_DATE]: "Pickup time and date confirmed",
  [ORDER_PROCESS.TRACK_SHIPMENT]: "Track shipment",
  [ORDER_PROCESS.SHIPMENT_PICKUP]: "Shipment Pickup",
  [ORDER_PROCESS.SHIPMENT_REACH_BUYER_WAREHOUSE]: "Shipment reached Buyer Warehouse"
});

export const BUYER_ORDER_PROCESS_LABEL = Object.freeze({
  [ORDER_PROCESS.OFFER_APPROVED]: "Offer Approved",
  [ORDER_PROCESS.UPLOAD_SHIPPING_DOCUMENTS]: "Seller to upload Serial Number",
  [ORDER_PROCESS.INSPECTION]: "Buyer Inspection Report",
  [ORDER_PROCESS.DONE]: "Done",
  [ORDER_PROCESS.CANCEL]: "Cancel",
  [ORDER_PROCESS.REVIEW]: "Review",
  [ORDER_PROCESS.GENERATE_TAX_INVOICE]: "Generate Tax Invoice",
  [ORDER_PROCESS.CHOOSE_THIRD_PARTY_PROVIDER]: "Choose Third Party Provider",
  [ORDER_PROCESS.FIRST_BID_AS_BUYER]: "First bid as buyer",
  [ORDER_PROCESS.FINAL_BID_AS_BUYER]: "Final bid as buyer",
  [ORDER_PROCESS.COUNTER_BID_AS_SELLER]: "Counter bid as seller",
  [ORDER_PROCESS.REJECTED_BID_AS_SELLER]: "Rejected bid as seller",
  [ORDER_PROCESS.PRODUCT_DELETED_AS_SELLER]: "product deleted as seller",
  [ORDER_PROCESS.CHOOSE_LOGISTICS_PROVIDER]: "Choose Logistics Provider",
  [ORDER_PROCESS.PROVIDE_SHIPPING_DETAILS]: "Seller to Provide Shipping Details",
  [ORDER_PROCESS.CONFIRM_PICKUP_DATE]: "Seller to Confirm Pickup time and date",
  [ORDER_PROCESS.TRACK_SHIPMENT]: "Track shipment",
  [ORDER_PROCESS.SHIPMENT_PICKUP]: "Shipment Pickup"
});

export const INSPECTION_IMAGE_TYPE = Object.freeze({
  INSPECTION_REJECT: "INSPECTION_REJECT",
  INSPECTION_ACCEPT: "INSPECTION_ACCEPT"
});

export const INSPECTION_REASON = Object.freeze({
  PRODUCT_TAMPERED: "The box has been Tampered",
  PRODUCT_DAMAGED_IN_TRANSIT: "The Goods were Damaged in transit"
});

export const DAYS_IN_MINUTES = range(0, 1440, 30);

export const WEEK_DAYS = Object.freeze({
  1: "Mon",
  2: "Tue",
  3: "Wed",
  4: "Thu",
  5: "Fri",
  6: "Sat",
  7: "Sun"
});

export const BADGE_TYPES = Object.freeze({
  STATUS_BADGE: "STATUS_BADGE",
  NUMBER_BADGE: "NUMBER_BADGE",
  VALUE_BADGE: "VALUE_BADGE"
});

export const BADGE_LEVELS = Object.freeze({
  [BADGE_TYPES.STATUS_BADGE]: {
    0: "Distributor",
    1: "Manufactor"
  },

  [BADGE_TYPES.NUMBER_BADGE]: {
    0: "blue",
    1: "bronze",
    2: "silver",
    3: "gold",
    4: "platinum"
  },
  [BADGE_TYPES.VALUE_BADGE]: {
    0: "blue",
    1: "bronze",
    2: "silver",
    3: "gold",
    4: "platinum"
  }
});

export const TEXT_HOVER_PENDING = Object.freeze({
  SELLER: "The response from your buyer will be delayed due to the time zone different",
  BUYER: "The response from your seller will be delayed due to the time zone different"
});

export const ACTION_LIST_TYPE = Object.freeze({
  // Subscribed product available
  PRODUCT_SUBSCRIPTION_AS_BUYER: "PRODUCT_SUBSCRIPTION_AS_BUYER",
  // Order
  UPLOAD_SERIAL_NUMBER_AS_SELLER: "UPLOAD_SERIAL_NUMBER_AS_SELLER",
  REVIEW_AS_SELLER: "REVIEW_AS_SELLER",
  REVIEW_AS_BUYER: "REVIEW_AS_BUYER",
  SHIPPING_DETAILS_AS_SELLER: "SHIPPING_DETAILS_AS_SELLER",
  SELECT_LOGISTIC_PROVIDER_AS_BUYER: "SELECT_LOGISTIC_PROVIDER_AS_BUYER",
  INSPECTION_REPORT_AS_BUYER: "INSPECTION_REPORT_AS_BUYER",
  INSPECTION_REPORT_FAIL_AS_SELLER: "INSPECTION_REPORT_FAIL_AS_SELLER",
  // Bid
  FIRST_BID_AS_BUYER: "FIRST_BID_AS_BUYER",
  FINAL_BID_AS_BUYER: "FINAL_BID_AS_BUYER",
  COUNTER_BID_AS_SELLER: "COUNTER_BID_AS_SELLER",
  REJECTED_BID_AS_SELLER: "REJECTED_BID_AS_SELLER",
  PRODUCT_DELETED_AS_SELLER: "PRODUCT_DELETED_AS_SELLER",
  // Approval
  REVIEW_SALE_AS_SELLER: "REVIEW_SALE_AS_SELLER"
});

export const ACTION_LIST_TYPE_LABEL = Object.freeze({
  [ACTION_LIST_TYPE.UPLOAD_SERIAL_NUMBER_AS_SELLER]: "Upload Serial Number",
  [ACTION_LIST_TYPE.REVIEW_AS_SELLER]: "Rate user",
  [ACTION_LIST_TYPE.REVIEW_AS_BUYER]: "Rate user",
  [ACTION_LIST_TYPE.SHIPPING_DETAILS_AS_SELLER]: "Provide Shipping Information",
  [ACTION_LIST_TYPE.SELECT_LOGISTIC_PROVIDER_AS_BUYER]: "Select Logistics Provider",
  [ACTION_LIST_TYPE.INSPECTION_REPORT_AS_BUYER]: "Shipment Arrived",
  [ACTION_LIST_TYPE.INSPECTION_REPORT_FAIL_AS_SELLER]: "Shipment challenged",

  [ACTION_LIST_TYPE.FIRST_BID_AS_BUYER]: "Respond to Bid Offer",
  [ACTION_LIST_TYPE.FINAL_BID_AS_BUYER]: "Respond to Final Bid Offer",
  [ACTION_LIST_TYPE.COUNTER_BID_AS_SELLER]: "Respond to Bid Offer",
  [ACTION_LIST_TYPE.REJECTED_BID_AS_SELLER]: "Bid rejected",
  [ACTION_LIST_TYPE.PRODUCT_DELETED_AS_SELLER]: "Sale Offer removed",
  [ACTION_LIST_TYPE.PRODUCT_SUBSCRIPTION_AS_BUYER]: "Subscribe Product Available",

  [ACTION_LIST_TYPE.REVIEW_SALE_AS_SELLER]: "Sale Offer Review"
});

export const NOTIFICATION_TYPE = Object.freeze({
  // Subscribe a Product
  BUYER_SUBSCRIBE: "BUYER_SUBSCRIBE",
  // Sale
  BUYER_SALE: "BUYER_SALE",
  SELLER_SALE: "SELLER_SALE",
  // Bid
  // Buyer
  BUYER_BID_COUNTER: "BUYER_BID_COUNTER",
  BUYER_BID_ACCEPTED: "BUYER_BID_ACCEPTED",
  BUYER_BID_REJECTED: "BUYER_BID_REJECTED",
  BUYER_BID_DELETED: "BUYER_BID_DELETED",
  // Seller
  SELLER_BID_COUNTER: "SELLER_BID_COUNTER",
  SELLER_BID_ACCEPTED: "SELLER_BID_ACCEPTED",
  SELLER_BID_REJECTED: "SELLER_BID_REJECTED",
  SELLER_BID_DELETED: "SELLER_BID_DELETED",
  SELLER_BID_FIRST: "SELLER_BID_FIRST",
  // Order
  SELLER_SERIAL_NUMBER: "SELLER_SERIAL_NUMBER",
  SELLER_SHIPPING_DETAILS: "SELLER_SHIPPING_DETAILS",
  SELLER_PREPARE_PICKUP: "SELLER_PREPARE_PICKUP",
  SELLER_FIRST_REMINDER_PICKUP: "SELLER_FIRST_REMINDER_PICKUP",
  SELLER_SECOND_REMINDER_PICKUP: "SELLER_SECOND_REMINDER_PICKUP",
  SELLER_PICKUP_SUCCESS: "SELLER_PICKUP_SUCCESS",
  SELLER_DELIVERY_SUCCESS: "SELLER_DELIVERY_SUCCESS",
  SELLER_INSPECTION: "SELLER_INSPECTION",
  SELLER_INSPECTION_PASS: "SELLER_INSPECTION_PASS",
  SELLER_INSPECTION_FAIL: "SELLER_INSPECTION_FAIL",
  SELLER_REVIEW: "SELLER_REVIEW",

  BUYER_SERIAL_NUMBER: "BUYER_SERIAL_NUMBER",
  BUYER_LOGISTIC_PROVIDER: "BUYER_LOGISTIC_PROVIDER",
  BUYER_SHIPMENT: "BUYER_SHIPMENT",
  BUYER_SHIPMENT_DOCUMENT: "BUYER_SHIPMENT_DOCUMENT",
  BUYER_PREPARE_PICKUP: "BUYER_PREPARE_PICKUP",
  BUYER_PICKUP_SUCCESS: "BUYER_PICKUP_SUCCESS",
  BUYER_INSPECTION: "BUYER_INSPECTION",
  BUYER_REVIEW: "BUYER_REVIEW",
  // Approval
  SELLER_SALE_PENDING: "SELLER_SALE_PENDING",
  SELLER_SALE_APPROVED: "SELLER_SALE_APPROVED",
  SELLER_SALE_REJECTED: "SELLER_SALE_REJECTED",
  SELLER_SALE_REVIEW: "SELLER_SALE_REVIEW"
});

export const MESUREMENT_UNITS = {
  SI: "SI",
  SU: "SU"
};

export const WEIGHT_UNITS = {
  KG: "kg",
  LB: "lb"
};

export const DIMENSION_UNITS = {
  CM: "cm",
  IN: "in"
};

export const FILE_TYPES = {
  EXCEL: "Excel",
  PDF: "PDF"
};

export const FILE_EXTENSIONS = Object.freeze({
  [FILE_TYPES.EXCEL]: ".xlsx,.xls",
  [FILE_TYPES.PDF]: ".pdf"
});

export const DOC_NAME_TYPES = Object.freeze({
  SERIAL_NUMBER: "SERIAL_NUMBER",
  COMMERCIAL_INVOICE: "COMMERCIAL_INVOICE",
  PURCHASE_ORDER: "PURCHASE_ORDER",
  LABEL_IMAGE: "LABEL_IMAGE",
  SHIPMENT_RECEIPT: "SHIPMENT_RECEIPT"
});

export const DOC_CODE_LABLES = Object.freeze({
  [DOC_NAME_TYPES.PURCHASE_ORDER]: "purchase-order",
  [DOC_NAME_TYPES.LABEL_IMAGE]: "label-image",
  [DOC_NAME_TYPES.COMMERCIAL_INVOICE]: "commercial-invoice",
  [DOC_NAME_TYPES.SHIPMENT_RECEIPT]: "shipment-receipt",
  [DOC_NAME_TYPES.SERIAL_NUMBER]: "serial-number"
});

export const DOC_NAME_LABLES = Object.freeze({
  [DOC_NAME_TYPES.SERIAL_NUMBER]: "Serial Number",
  [DOC_NAME_TYPES.PURCHASE_ORDER]: "Purchase Order",
  [DOC_NAME_TYPES.LABEL_IMAGE]: "Label Image",
  [DOC_NAME_TYPES.COMMERCIAL_INVOICE]: "Commercial Invoice",
  [DOC_NAME_TYPES.SHIPMENT_RECEIPT]: "Shipment Receipt"
});
