export const PERMISSION_LEVELS = Object.freeze({
  APPROVER: "APPROVER",
  VIEW_AND_ACTION: "VIEW_AND_ACTION",
  VIEW: "VIEW",
  NONE: "NONE"
});

export const PERMISSIONS_IDS = Object.freeze({
  ADMIN: "ADMIN",
  ANALYSIS_REPORT: "ANALYSIS_REPORT",
  PROFILE: "PROFILE",
  WALLET: "WALLET",
  ADJUST_TRADE_CREDIT: "ADJUST_TRADE_CREDIT",
  MANAGE_USER_INVENTORY: "MANAGE_USER_INVENTORY",
  POST_PRODUCT_DISTICHAIN: "POST_PRODUCT_DISTICHAIN",
  SET_NOTIFICATION_PRODUCT: "SET_NOTIFICATION_PRODUCT",
  BID_PRODUCT: "BID_PRODUCT",
  SERIAL_NUMBER: "SERIAL_NUMBER",
  INSPECTION_REPORT: "INSPECTION_REPORT",
  LOGISTICS_PROVIDER: "LOGISTICS_PROVIDER",
  PROVIDE_SHIPPING_INFORMATION: "PROVIDE_SHIPPING_INFORMATION",
  INSPECTION_PROVIDER: "INSPECTION_PROVIDER",
  SHIPMENT_TRACKING: "SHIPMENT_TRACKING",
  ORDER_TRACKING: "ORDER_TRACKING",
  CANCELLED_ORDER: "CANCELLED_ORDER",
  REVIEW_RATING: "REVIEW_RATING",
  OFFER_DISCOUNT: "OFFER_DISCOUNT",
  RESELL_ON_DISTICHAIN: "RESELL_ON_DISTICHAIN",
  RETURN_GOODS: "RETURN_GOODS",
  DOCUMENTS: "DOCUMENTS",
  ACCOUNT_SUMMARY: "ACCOUNT_SUMMARY"
});

export const PERMISSIONS = Object.freeze({
  ADMIN: {
    id: PERMISSIONS_IDS.ADMIN,
    description: "Admin",
    disabled: [
      PERMISSION_LEVELS.VIEW,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  ANALYSIS_REPORT: {
    id: PERMISSIONS_IDS.ANALYSIS_REPORT,
    description: "Analysis Report to be send by Mail",
    disabled: [PERMISSION_LEVELS.VIEW, PERMISSION_LEVELS.APPROVER]
  },
  PROFILE: {
    id: PERMISSIONS_IDS.PROFILE,
    description: "Profile",
    disabled: [PERMISSION_LEVELS.VIEW, PERMISSION_LEVELS.APPROVER]
  },
  WALLET: { id: PERMISSIONS_IDS.WALLET, description: "Wallet", disabled: [] },
  ADJUST_TRADE_CREDIT: {
    id: PERMISSIONS_IDS.ADJUST_TRADE_CREDIT,
    description: "Adjust Trade Credit",
    disabled: [PERMISSION_LEVELS.APPROVER]
  },
  MANAGE_USER_INVENTORY: {
    id: PERMISSIONS_IDS.MANAGE_USER_INVENTORY,
    description: "Manage User Inventory",
    disabled: [PERMISSION_LEVELS.APPROVER]
  },
  POST_PRODUCT_DISTICHAIN: {
    id: PERMISSIONS_IDS.POST_PRODUCT_DISTICHAIN,
    description: "Post a Product on Distichain",
    disabled: []
  },
  SET_NOTIFICATION_PRODUCT: {
    id: PERMISSIONS_IDS.SET_NOTIFICATION_PRODUCT,
    description: "Set Notificatication on a Product",
    disabled: [PERMISSION_LEVELS.VIEW, PERMISSION_LEVELS.APPROVER]
  },
  BID_PRODUCT: {
    id: PERMISSIONS_IDS.BID_PRODUCT,
    description: "Bid on a Product",
    disabled: [PERMISSION_LEVELS.APPROVER]
  },
  SERIAL_NUMBER: {
    id: PERMISSIONS_IDS.SERIAL_NUMBER,
    description: "Serial Number",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.APPROVER]
  },
  INSPECTION_REPORT: {
    id: PERMISSIONS_IDS.INSPECTION_REPORT,
    description: "Inspection Reports",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.APPROVER]
  },
  PROVIDE_SHIPPING_INFORMATION: {
    id: PERMISSIONS_IDS.PROVIDE_SHIPPING_INFORMATION,
    description: "Provide Shipping Information",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.APPROVER]
  },
  LOGISTICS_PROVIDER: {
    id: PERMISSIONS_IDS.LOGISTICS_PROVIDER,
    description: "Logitics Provider",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.APPROVER]
  },
  INSPECTION_PROVIDER: {
    id: PERMISSIONS_IDS.INSPECTION_PROVIDER,
    description: "Inspection Provider",
    disabled: [PERMISSION_LEVELS.NONE]
  },
  SHIPMENT_TRACKING: {
    id: PERMISSIONS_IDS.SHIPMENT_TRACKING,
    description: "Shipment Tracking",
    disabled: [
      PERMISSION_LEVELS.NONE,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  ORDER_TRACKING: {
    id: PERMISSIONS_IDS.ORDER_TRACKING,
    description: "Order Tracking",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.APPROVER]
  },
  CANCELLED_ORDER: {
    id: PERMISSIONS_IDS.CANCELLED_ORDER,
    description: "Cancelled Order",
    disabled: [
      PERMISSION_LEVELS.NONE,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  REVIEW_RATING: {
    id: PERMISSIONS_IDS.REVIEW_RATING,
    description: "Review and Rating",
    disabled: [PERMISSION_LEVELS.NONE, PERMISSION_LEVELS.VIEW, PERMISSION_LEVELS.APPROVER]
  },
  OFFER_DISCOUNT: {
    id: PERMISSIONS_IDS.OFFER_DISCOUNT,
    description: "Offer Discount",
    disabled: [
      PERMISSION_LEVELS.VIEW,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  RESELL_ON_DISTICHAIN: {
    id: PERMISSIONS_IDS.RESELL_ON_DISTICHAIN,
    description: "Resell on Distichain",
    disabled: [
      PERMISSION_LEVELS.VIEW,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  RETURN_GOODS: {
    id: PERMISSIONS_IDS.RETURN_GOODS,
    description: "Return Goods",
    disabled: [
      PERMISSION_LEVELS.VIEW,
      PERMISSION_LEVELS.VIEW_AND_ACTION,
      PERMISSION_LEVELS.APPROVER
    ]
  },
  DOCUMENTS: {
    id: PERMISSIONS_IDS.DOCUMENTS,
    description: "Documents",
    disabled: [PERMISSION_LEVELS.APPROVER]
  },
  ACCOUNT_SUMMARY: {
    id: PERMISSIONS_IDS.ACCOUNT_SUMMARY,
    description: "Account Summary",
    disabled: [PERMISSION_LEVELS.VIEW_AND_ACTION, PERMISSION_LEVELS.APPROVER]
  }
});
